# Service
server:
  port: 8081
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  context-path: /

# Spring
spring:
    view:
      suffix: .html
    datasource:
      # mysql
      url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      ## druid
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      poolPreparedStatements: true
      filters: stat,wall,slf4j
    http:
      multipart:
        maxFileSize: 10Mb
        maxRequestSize: 100Mb
    #---redis---#
    redis:
      host: 127.0.0.1
      port: 6379
      pool.max-idle: 8
      pool.min-idle: 0
      pool.max-active: 8
      pool.max-wait: -1
      timeout: 0

    #thymeleaf start
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      mode: LEGACYHTML5
      encoding: UTF-8
      content-type: text/html
    #thymeleaf end

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


## mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml



## FTP
webapp:
  name: onepaper
  path: classpath:/static/
net:
  ftp:
    imgurl: http://106.54.211.205/html
    host: 106.54.211.205
    username: ftpuser1
    password: jzpZSERDX!)!*
    encoding: gbk
  user:
    host: http://192.168.0.9:8090
  tpc:
    host: http://192.168.0.108:8080
  paper:
    host: http://192.168.0.108:8082

logging:
  level:
    com.charity.mapper : DEBUG

adai:
  file_url: E://